#!/bin/env inex

params: ${__fetch__:local/parameters.yaml}

logs_root: ${params.paths.logs_root}

plugins:
  - install_dependencies
  - download_rirs
  - download_musan
  - download_dev_clean
  - download_dev_other
  - download_test_clean
  - download_test_other
  - download_train_clean_100
  - download_train_clean_360
  - download_train_other_500
  - create_lists
  - compute_durations
  - prepare_train_data
  - prepare_valid_data
  - prepare_test_data
  - shuffle_chunks
  - train_model

install_dependencies:
  module: inex.helpers/stage
  options:
    config_path: local/install_dependencies.yaml
    final_path: ${logs_root}/00_install_dependencies/install_dependencies.yaml
    override:
      logs_dir: ${logs_root}/00_install_dependencies

download_rirs:
  module: inex.helpers/stage
  options:
    config_path: local/download_rirs.yaml
    final_path: ${logs_root}/01_prepare_rirs/download_rirs.yaml
    override:
      db_part_name: rirs_noises
      db_part_md5: e6f48e257286e05de56413b4779d8ffb
      logs_dir: ${logs_root}/01_prepare_rirs

download_musan:
  module: inex.helpers/stage
  options:
    config_path: local/download_musan.yaml
    final_path: ${logs_root}/02_prepare_musan/download_musan.yaml
    override:
      db_part_name: musan
      db_part_md5: 0c472d4fc0c5141eca47ad1ffeb2a7df
      logs_dir: ${logs_root}/02_prepare_musan

download_dev_clean:
  module: inex.helpers/stage
  options:
    config_path: local/download_librispeech.yaml
    final_path: ${logs_root}/03_prepare_librispeech/download_dev_clean.yaml
    override:
      db_part_name: dev-clean
      db_part_md5: 42e2234ba48799c1f50f24a7926300a1
      logs_dir: ${logs_root}/03_prepare_librispeech

download_dev_other:
  module: inex.helpers/stage
  options:
    config_path: local/download_librispeech.yaml
    final_path: ${logs_root}/03_prepare_librispeech/download_dev_other.yaml
    override:
      db_part_name: dev-other
      db_part_md5: c8d0bcc9cca99d4f8b62fcc847357931
      logs_dir: ${logs_root}/03_prepare_librispeech

download_test_clean:
  module: inex.helpers/stage
  options:
    config_path: local/download_librispeech.yaml
    final_path: ${logs_root}/03_prepare_librispeech/download_test_clean.yaml
    override:
      db_part_name: test-clean
      db_part_md5: 32fa31d27d2e1cad72775fee3f4849a9
      logs_dir: ${logs_root}/03_prepare_librispeech

download_test_other:
  module: inex.helpers/stage
  options:
    config_path: local/download_librispeech.yaml
    final_path: ${logs_root}/03_prepare_librispeech/download_test_other.yaml
    override:
      db_part_name: test-other
      db_part_md5: fb5a50374b501bb3bac4815ee91d3135
      logs_dir: ${logs_root}/03_prepare_librispeech

download_train_clean_100:
  module: inex.helpers/stage
  options:
    config_path: local/download_librispeech.yaml
    final_path: ${logs_root}/03_prepare_librispeech/download_train_clean_100.yaml
    override:
      db_part_name: train-clean-100
      db_part_md5: 2a93770f6d5c6c964bc36631d331a522
      logs_dir: ${logs_root}/03_prepare_librispeech

download_train_clean_360:
  module: inex.helpers/stage
  options:
    config_path: local/download_librispeech.yaml
    final_path: ${logs_root}/03_prepare_librispeech/download_train_clean_360.yaml
    override:
      db_part_name: train-clean-360
      db_part_md5: c0e676e450a7ff2f54aeade5171606fa
      logs_dir: ${logs_root}/03_prepare_librispeech

download_train_other_500:
  module: inex.helpers/stage
  options:
    config_path: local/download_librispeech.yaml
    final_path: ${logs_root}/03_prepare_librispeech/download_train_other_500.yaml
    override:
      db_part_name: train-other-500
      db_part_md5: d1a0fd59409feb2c614ce4d30c387708
      logs_dir: ${logs_root}/03_prepare_librispeech
    disable: true

create_lists:
  module: inex.helpers/stage
  options:
    config_path: local/create_lists.yaml
    final_path: ${logs_root}/04_create_lists/create_lists.yaml
    title: 'Creating train, valid and test data lists'
    done_mark: ${logs_root}/04_create_lists/create_lists.done

compute_durations:
  module: inex.helpers/stage
  options:
    config_path: local/compute_durations.yaml
    final_path: ${logs_root}/05_compute_durations/compute_durations.yaml
    title: 'Calculating duration of utterances'
    done_mark: ${logs_root}/05_compute_durations/compute_durations.done

prepare_train_data:
  module: inex.helpers/stage
  options:
    config_path: local/prepare_data.yaml
    final_path: ${logs_root}/06_prepare_data/prepare_train_data.yaml
    title: 'Preparing train data chunks'
    override:
      vad_align: ${params.align.train_vad}
      wav_scp: ${params.paths.train_scp}
      utt2dur: ${params.paths.train_dur}
      data_dir: ${params.paths.train_data_dir}
      num_repeats: ${params.feats.train_repeats}
      num_per_utt: ${params.chunk.train_num_per_utt}
      num_chunks: ${params.chunk.train_num_chunks}
    done_mark: ${logs_root}/06_prepare_data/prepare_train_data.done

prepare_valid_data:
  module: inex.helpers/stage
  options:
    config_path: local/prepare_data.yaml
    final_path: ${logs_root}/06_prepare_data/prepare_valid_data.yaml
    title: 'Preparing valid data chunks'
    override:
      vad_align: ${params.align.valid_vad}
      wav_scp: ${params.paths.valid_scp}
      utt2dur: ${params.paths.valid_dur}
      data_dir: ${params.paths.valid_data_dir}
      num_repeats: ${params.feats.valid_repeats}
      num_per_utt: ${params.chunk.valid_num_per_utt}
      num_chunks: ${params.chunk.valid_num_chunks}
    done_mark: ${logs_root}/06_prepare_data/prepare_valid_data.done
    force: true

prepare_test_data:
  module: inex.helpers/stage
  options:
    config_path: local/prepare_data.yaml
    final_path: ${logs_root}/06_prepare_data/prepare_test_data.yaml
    title: 'Preparing test data chunks'
    override:
      vad_align: ${params.align.test_vad}
      wav_scp: ${params.paths.test_scp}
      utt2dur: ${params.paths.test_dur}
      data_dir: ${params.paths.test_data_dir}
      num_repeats: ${params.feats.test_repeats}
      num_per_utt: ${params.chunk.test_num_per_utt}
      num_chunks: ${params.chunk.test_num_chunks}
    done_mark: ${logs_root}/06_prepare_data/prepare_test_data.done

shuffle_chunks:
  module: inex.helpers/stage
  options:
    config_path: local/shuffle_chunks.yaml
    final_path: ${logs_root}/06_prepare_data/shuffle_chunks.yaml
    title: 'Shuffling training chunks'
    override:
      batch_size: ${params.shuffle.batch_size}
      num_workers: ${params.shuffle.num_workers}
      compress: ${params.chunk.compress}
      data_dir: ${params.paths.train_data_dir}
    done_mark: ${logs_root}/06_prepare_data/shuffle_chunks.done

train_model:
  module: inex.helpers/stage
  options:
    config_path: local/train_model.yaml
    final_path: ${logs_root}/07_train_model/train_model.yaml
    title: 'Training model'
    override:
      targ_from_chid: ${params.loader.targ_from_chid}
      classes_path: ${params.paths.classes}
      valid_data_dir: ${params.paths.valid_data_dir}
      train_data_dir: ${params.paths.train_data_dir}
      batch_size: ${params.loader.batch_size}
      num_workers: ${params.loader.num_workers}
      pin_memory: ${params.loader.pin_memory}
      model_config: ${params.model.config}
      lr: ${params.train.lr}
      num_epochs: ${params.train.num_epochs}
      stop_after: ${params.train.stop_after}
      resume_training: ${params.train.resume_training}
      accelerator: ${params.train.accelerator}
      devices: ${params.train.devices}
      num_nodes: ${params.train.num_nodes}
      ddp_strategy: ${params.train.ddp_strategy}
      val_check_interval: ${params.train.val_check_interval}
      log_aver_num: ${params.train.log_aver_num}
      train_dir: ${params.paths.train_dir}
    done_mark: ${logs_root}/07_train_model/train_model.done
    force: true